parameters:
  serializer.cache_dir: '%kernel.cache_dir%'
  serializer.check_timestamp: '%kernel.debug%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Serializer\ClassFactory:
    arguments:
      $cachePath: '%serializer.cache_dir%'
      $checkTimestamp: '%serializer.check_timestamp%'

  Serializer\JsonSerializer: ~
